package com.ing.sea.pdeng.graph.search.testcases

import com.ing.sea.pdeng.graph.{Type, Vertex}
import com.ing.sea.pdeng.graph.search.TraversalTest
import com.ing.sea.pdeng.graph.Vertex.{cu, e, t}
import scalax.collection.Graph
import scalax.collection.edge.WDiHyperEdge

object CompleteHelloWorldModel {
  def apply(): TraversalTest = new CompleteHelloWorldModel()
}

class CompleteHelloWorldModel extends TraversalTest {
  val e34 = e(t("domain.Monetary.EURList"), cu("domain.Monetary.LifteurlistIntoEURListList"), t("domain.Monetary.EURListList"))
  val e66 = e(t("domain.Savings.SavingsAgreementDetails"), cu("domain.Savings.LiftsavingsagreementdetailsIntoSavingsAgreementDetailsList"), t("domain.Savings.SavingsAgreementDetailsList"))
  val e75 = e(t("domain.Savings.SavingsMeResponseList"), cu("domain.Savings.FMapSavingsMeResponseToSavingsAgreementDetailsListOnSavingsMeResponseListList"), t("domain.Savings.SavingsAgreementDetailsListList"))
  val e24 = e(t("domain.CustomerInformation.CustomerId"), cu("domain.CustomerInformation.LiftcustomeridIntoCustomerIdList"), t("domain.CustomerInformation.CustomerIdList"))
  val e54 = e(t("domain.Savings.SavingsMeResponseList"), cu("domain.Savings.LiftsavingsmeresponselistIntoSavingsMeResponseListList"), t("domain.Savings.SavingsMeResponseListList"))
  val e65 = e(t("domain.Monetary.Money"), cu("domain.Monetary.MoneyToCurrency"), t("domain.Monetary.Currency"))
  val e50 = e(t("domain.CustomerInformation.CustomerIdList"), cu("domain.CustomerInformation.LiftcustomeridlistIntoCustomerIdListList"), t("domain.CustomerInformation.CustomerIdListList"))
  val e70 = e(t("Nothing"), cu("LiftnothingIntoNothingList"), t("NothingList"))
  val e67 = e(t("domain.Cards.CardArrangementList"), cu("domain.Cards.FMapListCardDetailsOnCardArrangementListList"), t("domain.Cards.CardDetailsList"))
  val e21 = e(t("domain.Monetary.MonetaryAmountList"), cu("domain.Monetary.FMapMonetaryAmountToDecimalPlaceOnMonetaryAmountListList"), t("domain.Monetary.DecimalPlaceList"))
  val e84 = e(t("domain.Savings.SavingsMeResponse"), cu("domain.Savings.LiftsavingsmeresponseIntoSavingsMeResponseList"), t("domain.Savings.SavingsMeResponseList"))
  val e14 = e(t("domain.Savings.SavingsMeResponse"), cu("domain.Savings.SavingsMeResponseToCustomerId"), t("domain.CustomerInformation.CustomerId"))
  val e63 = e(t("domain.Savings.SavingsMeResponseWrongList"), cu("domain.Savings.LiftsavingsmeresponsewronglistIntoSavingsMeResponseWrongListList"), t("domain.Savings.SavingsMeResponseWrongListList"))
  val e83 = e(t("domain.Monetary.Currency"), cu("domain.Monetary.LiftcurrencyIntoCurrencyList"), t("domain.Monetary.CurrencyList"))
  val e27 = e(t("domain.Cards.CardArrangement"), cu("domain.Cards.LiftcardarrangementIntoCardArrangementList"), t("domain.Cards.CardArrangementList"))
  val e74 = e(t("domain.Monetary.CurrencyList"), cu("domain.Monetary.LiftcurrencylistIntoCurrencyListList"), t("domain.Monetary.CurrencyListList"))
  val e1 = e(t("domain.CustomerInformation.PartyAgreement"), t("domain.Monetary.Money"), t("domain.CustomerInformation.AccountNumber"), cu("domain.Savings.PartyAgreementMoneyAccountNumberToSavingsAgreementDetails"), t("domain.Savings.SavingsAgreementDetails"))
  val e57 = e(t("domain.Savings.SavingsAgreementDetails"), cu("domain.Savings.SavingsAgreementDetailsToAccountNumber"), t("domain.CustomerInformation.AccountNumber"))
  val e42 = e(t("Boolean"), cu("LiftbooleanIntoBooleanList"), t("BooleanList"))
  val e10 = e(t("ZonedDateTimeList"), cu("LiftzoneddatetimelistIntoZonedDateTimeListList"), t("ZonedDateTimeListList"))
  val e91 = e(t("domain.CustomerInformation.PartyAgreementList"), cu("domain.Savings.FMapFooOnPartyAgreementListList"), t("domain.CustomerInformation.PartyAgreementList"))
  val e45 = e(t("domain.Savings.SavingsMeResponseWrongList"), cu("domain.Savings.FMapSavingsMeResponseWrongToSavingsAgreementDetailsOnSavingsMeResponseWrongListList"), t("domain.Savings.SavingsAgreementDetailsList"))
  val e19 = e(t("domain.Monetary.DecimalPlace"), cu("domain.Monetary.LiftdecimalplaceIntoDecimalPlaceList"), t("domain.Monetary.DecimalPlaceList"))
  val e33 = e(t("StringList"), cu("LiftstringlistIntoStringListList"), t("StringListList"))
  val e53 = e(t("NothingList"), cu("LiftnothinglistIntoNothingListList"), t("NothingListList"))
  val e40 = e(t("domain.Cards.CardDetailsList"), cu("domain.Cards.LiftcarddetailslistIntoCardDetailsListList"), t("domain.Cards.CardDetailsListList"))
  val e20 = e(t("NumberList"), cu("LiftnumberlistIntoNumberListList"), t("NumberListList"))
  val e90 = e(t("domain.CustomerInformation.CustomerId"), cu("domain.Savings.GPAS"), t("domain.CustomerInformation.PartyAgreementList"))
  val e60 = e(t("domain.CustomerInformation.PartyAgreementList"), cu("domain.CustomerInformation.LiftpartyagreementlistIntoPartyAgreementListList"), t("domain.CustomerInformation.PartyAgreementListList"))
  val e7 = e(t("Number"), cu("LiftnumberIntoNumberList"), t("NumberList"))
  val e87 = e(t("domain.Cards.CardArrangementList"), cu("domain.Cards.LiftcardarrangementlistIntoCardArrangementListList"), t("domain.Cards.CardArrangementListList"))
  val e32 = e(t("domain.Savings.SavingsMeResponseWrong"), cu("domain.Savings.LiftsavingsmeresponsewrongIntoSavingsMeResponseWrongList"), t("domain.Savings.SavingsMeResponseWrongList"))
  val e55 = e(t("String"), t("StringList"), cu("domain.Cards.fooStringListToInt"), t("Int"))
  val e52 = e(t("IntList"), cu("LiftintlistIntoIntListList"), t("IntListList"))
  val e81 = e(t("domain.Savings.SavingsAgreementDetails"), cu("domain.Savings.SavingsAgreementDetailsToPartyAgreement"), t("domain.CustomerInformation.PartyAgreement"))
  val e0 = e(t("domain.Savings.SavingsAgreementDetailsList"), cu("domain.Savings.FMapSavingsAgreementDetailsToMoneyOnSavingsAgreementDetailsListList"), t("domain.Monetary.MoneyList"))
  val e88 = e(t("domain.Monetary.Money"), cu("domain.Monetary.MoneyToMonetaryAmount"), t("domain.Monetary.MonetaryAmount"))
  val e59 = e(t("domain.CustomerInformation.AgreementId"), cu("domain.CustomerInformation.LiftagreementidIntoAgreementIdList"), t("domain.CustomerInformation.AgreementIdList"))
  val e18 = e(t("ZonedDateList"), cu("LiftzoneddatelistIntoZonedDateListList"), t("ZonedDateListList"))
  val e41 = e(t("domain.Japan.YEN"), cu("domain.Japan.LiftyenIntoYENList"), t("domain.Japan.YENList"))
  val e89 = e(t("domain.Monetary.MonetaryAmountList"), cu("domain.Monetary.LiftmonetaryamountlistIntoMonetaryAmountListList"), t("domain.Monetary.MonetaryAmountListList"))
  val e29 = e(t("domain.Cards.CardArrangement"), cu("domain.Cards.ListCardDetails"), t("domain.Cards.CardDetails"))
  val e2 = e(t("Int"), cu("LiftintIntoIntList"), t("IntList"))
  val e25 = e(t("domain.CustomerInformation.PartyAgreement"), cu("domain.CustomerInformation.LiftpartyagreementIntoPartyAgreementList"), t("domain.CustomerInformation.PartyAgreementList"))
  val e11 = e(t("domain.Monetary.USD"), cu("domain.Monetary.LiftusdIntoUSDList"), t("domain.Monetary.USDList"))
  val e62 = e(t("domain.Savings.SavingsMeResponseWrongList"), cu("domain.Savings.FMapSavingsMeResponseWrongToCustomerIdOnSavingsMeResponseWrongListList"), t("domain.CustomerInformation.CustomerIdList"))
  val e22 = e(t("domain.CustomerInformation.CustomerId"), t("domain.Savings.SavingsAgreementDetails"), cu("domain.Savings.CustomerIdSavingsAgreementDetailsToSavingsMeResponseWrong"), t("domain.Savings.SavingsMeResponseWrong"))
  val e39 = e(t("domain.Monetary.MonetaryAmount"), cu("domain.Monetary.MonetaryAmountToDecimalPlace"), t("domain.Monetary.DecimalPlace"))
  val e44 = e(t("UUIDList"), cu("LiftuuidlistIntoUUIDListList"), t("UUIDListList"))
  val e49 = e(t("UUID"), cu("LiftuuidIntoUUIDList"), t("UUIDList"))
  val e72 = e(t("domain.Monetary.MoneyList"), cu("domain.Monetary.LiftmoneylistIntoMoneyListList"), t("domain.Monetary.MoneyListList"))
  val e17 = e(t("domain.Monetary.MonetaryAmount"), cu("domain.Monetary.LiftmonetaryamountIntoMonetaryAmountList"), t("domain.Monetary.MonetaryAmountList"))
  val e73 = e(t("domain.CustomerInformation.CustomerIdList"), cu("domain.Savings.FMapGPASOnCustomerIdListList"), t("domain.CustomerInformation.PartyAgreementListList"))
  val e31 = e(t("domain.Monetary.DigitsList"), cu("domain.Monetary.LiftdigitslistIntoDigitsListList"), t("domain.Monetary.DigitsListList"))
  val e9 = e(t("domain.Monetary.DecimalPlaceList"), cu("domain.Monetary.LiftdecimalplacelistIntoDecimalPlaceListList"), t("domain.Monetary.DecimalPlaceListList"))
  val e5 = e(t("Long"), cu("LiftlongIntoLongList"), t("LongList"))
  val e82 = e(t("domain.Monetary.Currency"), t("domain.Monetary.MonetaryAmount"), cu("domain.Monetary.CurrencyMonetaryAmountToMoney"), t("domain.Monetary.Money"))
  val e38 = e(t("domain.CustomerInformation.PartyAgreement"), cu("domain.Savings.Foo"), t("domain.CustomerInformation.PartyAgreement"))
  val e69 = e(t("domain.Savings.SavingsAgreementDetails"), cu("domain.Savings.SavingsAgreementDetailsToMoney"), t("domain.Monetary.Money"))
  val e48 = e(t("domain.Japan.YENList"), cu("domain.Japan.LiftyenlistIntoYENListList"), t("domain.Japan.YENListList"))
  val e64 = e(t("domain.Monetary.Digits"), t("domain.Monetary.DecimalPlace"), cu("domain.Monetary.DigitsDecimalPlaceToMonetaryAmount"), t("domain.Monetary.MonetaryAmount"))
  val e35 = e(t("domain.CustomerInformation.PartyAgreement"), cu("domain.Savings.IDOSA"), t("domain.Savings.SavingsAgreementDetails"))
  val e12 = e(t("ZonedDateTime"), cu("LiftzoneddatetimeIntoZonedDateTimeList"), t("ZonedDateTimeList"))
  val e30 = e(t("LongList"), cu("LiftlonglistIntoLongListList"), t("LongListList"))
  val e80 = e(t("domain.Monetary.USDList"), cu("domain.Monetary.LiftusdlistIntoUSDListList"), t("domain.Monetary.USDListList"))
  val e78 = e(t("domain.CustomerInformation.AccountNumber"), cu("domain.CustomerInformation.LiftaccountnumberIntoAccountNumberList"), t("domain.CustomerInformation.AccountNumberList"))
  val e8 = e(t("domain.Monetary.MonetaryAmount"), cu("domain.Monetary.MonetaryAmountToDigits"), t("domain.Monetary.Digits"))
  val e26 = e(t("domain.CustomerInformation.AccountNumberList"), cu("domain.CustomerInformation.LiftaccountnumberlistIntoAccountNumberListList"), t("domain.CustomerInformation.AccountNumberListList"))
  val e43 = e(t("domain.Savings.SavingsMeResponseWrong"), cu("domain.Savings.SavingsMeResponseWrongToSavingsAgreementDetails"), t("domain.Savings.SavingsAgreementDetails"))
  val e46 = e(t("domain.Monetary.MonetaryAmountList"), cu("domain.Monetary.FMapMonetaryAmountToDigitsOnMonetaryAmountListList"), t("domain.Monetary.DigitsList"))
  val e36 = e(t("domain.Savings.SavingsMeResponseList"), cu("domain.Savings.FMapSavingsMeResponseToCustomerIdOnSavingsMeResponseListList"), t("domain.CustomerInformation.CustomerIdList"))
  val e6 = e(t("domain.Savings.SavingsAgreementDetailsList"), cu("domain.Savings.FMapSavingsAgreementDetailsToAccountNumberOnSavingsAgreementDetailsListList"), t("domain.CustomerInformation.AccountNumberList"))
  val e23 = e(t("domain.Monetary.Digits"), cu("domain.Monetary.LiftdigitsIntoDigitsList"), t("domain.Monetary.DigitsList"))
  val e4 = e(t("domain.CustomerInformation.CustomerId"), t("domain.Savings.SavingsAgreementDetailsList"), cu("domain.Savings.CustomerIdSavingsAgreementDetailsListToSavingsMeResponse"), t("domain.Savings.SavingsMeResponse"))
  val e58 = e(t("BooleanList"), cu("LiftbooleanlistIntoBooleanListList"), t("BooleanListList"))
  val e28 = e(t("String"), cu("LiftstringIntoStringList"), t("StringList"))
  val e56 = e(t("domain.CustomerInformation.PartyAgreementList"), cu("domain.CustomerInformation.FMapPartyAgreementToAgreementIdOnPartyAgreementListList"), t("domain.CustomerInformation.AgreementIdList"))
  val e16 = e(t("domain.CustomerInformation.PartyAgreementList"), cu("domain.Savings.FMapIDOSAOnPartyAgreementListList"), t("domain.Savings.SavingsAgreementDetailsList"))
  val e61 = e(t("domain.Cards.CardDetails"), cu("domain.Cards.LiftcarddetailsIntoCardDetailsList"), t("domain.Cards.CardDetailsList"))
  val e79 = e(t("domain.Monetary.EUR"), cu("domain.Monetary.LifteurIntoEURList"), t("domain.Monetary.EURList"))
  val e13 = e(t("domain.Monetary.MoneyList"), cu("domain.Monetary.FMapMoneyToCurrencyOnMoneyListList"), t("domain.Monetary.CurrencyList"))
  val e76 = e(t("domain.Savings.SavingsMeResponseWrong"), cu("domain.Savings.SavingsMeResponseWrongToCustomerId"), t("domain.CustomerInformation.CustomerId"))
  val e71 = e(t("domain.CustomerInformation.AgreementId"), cu("domain.CustomerInformation.AgreementIdToPartyAgreement"), t("domain.CustomerInformation.PartyAgreement"))
  val e85 = e(t("domain.CustomerInformation.AgreementIdList"), cu("domain.CustomerInformation.LiftagreementidlistIntoAgreementIdListList"), t("domain.CustomerInformation.AgreementIdListList"))
  val e47 = e(t("domain.Savings.SavingsMeResponse"), cu("domain.Savings.SavingsMeResponseToSavingsAgreementDetailsList"), t("domain.Savings.SavingsAgreementDetailsList"))
  val e77 = e(t("domain.Savings.SavingsAgreementDetailsList"), cu("domain.Savings.LiftsavingsagreementdetailslistIntoSavingsAgreementDetailsListList"), t("domain.Savings.SavingsAgreementDetailsListList"))
  val e3 = e(t("domain.Monetary.Money"), cu("domain.Monetary.LiftmoneyIntoMoneyList"), t("domain.Monetary.MoneyList"))
  val e86 = e(t("domain.Monetary.MoneyList"), cu("domain.Monetary.FMapMoneyToMonetaryAmountOnMoneyListList"), t("domain.Monetary.MonetaryAmountList"))
  val e68 = e(t("ZonedDate"), cu("LiftzoneddateIntoZonedDateList"), t("ZonedDateList"))
  val e51 = e(t("domain.CustomerInformation.AgreementIdList"), cu("domain.CustomerInformation.FMapAgreementIdToPartyAgreementOnAgreementIdListList"), t("domain.CustomerInformation.PartyAgreementList"))
  val e15 = e(t("domain.CustomerInformation.PartyAgreement"), cu("domain.CustomerInformation.PartyAgreementToAgreementId"), t("domain.CustomerInformation.AgreementId"))
  val e37 = e(t("domain.Savings.SavingsAgreementDetailsList"), cu("domain.Savings.FMapSavingsAgreementDetailsToPartyAgreementOnSavingsAgreementDetailsListList"), t("domain.CustomerInformation.PartyAgreementList"))

  override val target: Type = t("domain.Savings.SavingsMeResponse")
  override val available: Set[Type] = Set(
    t("domain.CustomerInformation.CustomerId")
  )
  override val graph: Graph[Vertex, WDiHyperEdge] = Graph(e34, e66, e75, e24, e54, e65, e50, e70, e67, e21, e84, e14, e63, e83, e27, e74, e1, e57, e42, e10, e91, e45, e19, e33, e53, e40, e20, e90, e60, e7, e87, e32, e55, e52, e81, e0, e88, e59, e18, e41, e89, e29, e2, e25, e11, e62, e22, e39, e44, e49, e72, e17, e73, e31, e9, e5, e82, e38, e69, e48, e64, e35, e12, e30, e80, e78, e8, e26, e43, e46, e36, e6, e23, e4, e58, e28, e56, e16, e61, e79, e13, e76, e71, e85, e47, e77, e3, e86, e68, e51, e15, e37)
  override val maxDepth: Int = Integer.MAX_VALUE
  override val expectedResults: List[List[WDiHyperEdge[Vertex]]] = List(
    List(
      e(t("domain.CustomerInformation.CustomerId"), cu("domain.Savings.GPAS"), t("domain.CustomerInformation.PartyAgreementList")),
      e(t("domain.CustomerInformation.CustomerId"), t("domain.Savings.SavingsAgreementDetailsList"), cu("domain.Savings.CustomerIdSavingsAgreementDetailsListToSavingsMeResponse"), t("domain.Savings.SavingsMeResponse")),
      e(t("domain.CustomerInformation.PartyAgreementList"), cu("domain.Savings.FMapIDOSAOnPartyAgreementListList"), t("domain.Savings.SavingsAgreementDetailsList"))
    )
  )
}